[platformio]
default_envs = esp32s3S

[env:esp32s3S]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -Iinclude -DSERVER
              -Wl,--print-memory-usage
              -Wl,-Map,.pio/build/esp32s3/firmware.map
lib_deps = ESP32Async/AsyncTCP @ ^3.4.10
           olikraus/U8g2
           gpsLib=symlink://../gpsLib
           wifiLan=symlink://../wifiLan

build_type = debug
debug_tool = esp-builtin
debug_init_break = tbreak setup

; upload_port = COM8
; monitor_port = COM10
upload_speed  = 921600
monitor_speed = 115200
upload_port   = /dev/tty.wchusbserial5B910983571
monitor_port  = /dev/tty.wchusbserial5B910983571

[env:esp32s3C]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -Iinclude -DCLIENT
              -Wl,--print-memory-usage
              -Wl,-Map,.pio/build/esp32s3/firmware.map
lib_deps = ESP32Async/AsyncTCP @ ^3.4.10
           olikraus/U8g2
           gpsLib=symlink://../gpsLib
           wifiLan=symlink://../wifiLan

build_type = debug
debug_tool = esp-builtin
debug_init_break = tbreak setup

; upload_port = COM12
; monitor_port = COM13
upload_speed  = 921600
monitor_speed = 115200
upload_port   = /dev/tty.wchusbserial5B910980841
monitor_port  = /dev/tty.wchusbserial5B910980841
